# Generated by Django 2.2.5 on 2022-01-22 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('volume_filename', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('case_history', models.CharField(max_length=100)),
            ],
        ),
    ]
